#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : oslo.messaging
Version  : 8.1.0
Release  : 64
URL      : https://tarballs.openstack.org/oslo.messaging/oslo.messaging-8.1.0.tar.gz
Source0  : https://tarballs.openstack.org/oslo.messaging/oslo.messaging-8.1.0.tar.gz
Source99 : https://tarballs.openstack.org/oslo.messaging/oslo.messaging-8.1.0.tar.gz.asc
Summary  : Oslo Messaging API
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.messaging-bin
Requires: oslo.messaging-python3
Requires: oslo.messaging-license
Requires: oslo.messaging-python
Requires: PyYAML
Requires: Sphinx
Requires: WebOb
Requires: amqp
Requires: bandit
Requires: cachetools
Requires: coverage
Requires: debtcollector
Requires: eventlet
Requires: fixtures
Requires: futures
Requires: futurist
Requires: greenlet
Requires: hacking
Requires: kombu
Requires: monotonic
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.middleware
Requires: oslo.serialization
Requires: oslo.service
Requires: oslo.utils
Requires: oslotest
Requires: pbr
Requires: python-mock
Requires: pyzmq
Requires: redis
Requires: reno
Requires: six
Requires: stevedore
Requires: tenacity
Requires: testscenarios
Requires: testtools
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Team and repository tags
        ========================

%package bin
Summary: bin components for the oslo.messaging package.
Group: Binaries
Requires: oslo.messaging-license

%description bin
bin components for the oslo.messaging package.


%package license
Summary: license components for the oslo.messaging package.
Group: Default

%description license
license components for the oslo.messaging package.


%package python
Summary: python components for the oslo.messaging package.
Group: Default
Requires: oslo.messaging-python3

%description python
python components for the oslo.messaging package.


%package python3
Summary: python3 components for the oslo.messaging package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oslo.messaging package.


%prep
%setup -q -n oslo.messaging-8.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532269274
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/oslo.messaging
cp LICENSE %{buildroot}/usr/share/doc/oslo.messaging/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/oslo-messaging-send-notification
/usr/bin/oslo-messaging-zmq-broker
/usr/bin/oslo-messaging-zmq-proxy

%files license
%defattr(-,root,root,-)
/usr/share/doc/oslo.messaging/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
