#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oslo.messaging
Version  : 1.8.3
Release  : 24
URL      : http://tarballs.openstack.org/oslo.messaging/oslo.messaging-1.8.3.tar.gz
Source0  : http://tarballs.openstack.org/oslo.messaging/oslo.messaging-1.8.3.tar.gz
Summary  : Oslo Messaging API
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.messaging-bin
Requires: oslo.messaging-python
BuildRequires : Babel-python
BuildRequires : Jinja2-python
BuildRequires : PyYAML-python
BuildRequires : Pygments-python
BuildRequires : Sphinx-python
BuildRequires : WebOb-python
BuildRequires : aioeventlet-python
BuildRequires : amqp-python
BuildRequires : anyjson-python
BuildRequires : coverage-python
BuildRequires : discover-python
BuildRequires : docutils-python
BuildRequires : eventlet-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : fixtures-python
BuildRequires : flake8-python
BuildRequires : futures-python
BuildRequires : greenlet-python
BuildRequires : hacking-python
BuildRequires : iso8601-python
BuildRequires : kombu-python
BuildRequires : linecache2-python
BuildRequires : markupsafe-python
BuildRequires : mccabe-python
BuildRequires : mox3-python
BuildRequires : msgpack-python-python
BuildRequires : netaddr-python
BuildRequires : netifaces-python
BuildRequires : oslo.config-python
BuildRequires : oslo.context-python
BuildRequires : oslo.i18n-python
BuildRequires : oslo.middleware-python
BuildRequires : oslo.serialization-python
BuildRequires : oslo.utils-python
BuildRequires : oslosphinx-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pep8-python
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyflakes-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mimeparse-python
BuildRequires : python-mock
BuildRequires : python-subunit-python
BuildRequires : pytz-python
BuildRequires : pyzmq-python
BuildRequires : qpid-python-python
BuildRequires : redis-python
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : stevedore-python
BuildRequires : testrepository-python
BuildRequires : testscenarios
BuildRequires : testscenarios-python
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : trollius-python
BuildRequires : unittest2-python
BuildRequires : virtualenv
Patch1: 0001-Allow-to-remove-second-_send_reply-call.patch
Patch2: 0002-Refactor-processing-reply-in-ReplyWaiter.patch
Patch3: 0003-Speedy-Gonzalez-rabbitmq-message-trace.patch

%description
Oslo Messaging Library
======================
The Oslo messaging API supports RPC and notifications over a number of
different messaging transports.

%package bin
Summary: bin components for the oslo.messaging package.
Group: Binaries

%description bin
bin components for the oslo.messaging package.


%package python
Summary: python components for the oslo.messaging package.
Group: Default

%description python
python components for the oslo.messaging package.


%prep
%setup -q -n oslo.messaging-1.8.3
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python2 setup.py test
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/oslo-messaging-zmq-receiver

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
